/* CloudSkin content-snapshot baker.
   Regenerates js/content-snapshot.js from the LIVE cloudskin_content table so the
   deploy-time snapshot always equals production. If it is stale, the site paints the
   old photo on the first frame and then swaps to the live one (the "default picture
   renders first" flash); a fresh snapshot == live means content.js mapsEqual() is true
   and the live fetch returns early, so there is no swap.

   Reads the PUBLIC Supabase url + anon key straight from js/supabase-config.js (the same
   read-only SELECT the site itself uses - no secret involved).

   FAIL-SAFE: on any fetch / empty-table / verify failure it leaves the existing snapshot
   UNTOUCHED and sets a non-zero exit code, so a deploy that runs this (scripts/deploy.mjs)
   ABORTS rather than shipping a broken or empty snapshot.

   Usage:  node scripts/bake-content.mjs            (writes js/content-snapshot.js)
           node scripts/bake-content.mjs --check    (verify only, do NOT write)

   NB: uses process.exitCode (never process.exit()) so it exits cleanly after fetch on
   Windows - a bare process.exit() while undici keep-alive sockets are open crashes libuv. */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const CFG = path.join(ROOT, 'js', 'supabase-config.js');
const OUT = path.join(ROOT, 'js', 'content-snapshot.js');
const CHECK = process.argv.includes('--check');

function fail(msg) { console.error('BAKE FAILED: ' + msg + ' (existing snapshot left untouched)'); process.exitCode = 1; }

function deepEqual(a, b) {
  const ak = Object.keys(a), bk = Object.keys(b);
  if (ak.length !== bk.length) return { ok: false, why: 'key count ' + ak.length + ' vs ' + bk.length };
  for (const k of ak) {
    if (!(k in b)) return { ok: false, why: 'missing ' + k };
    if (String(a[k]) !== String(b[k])) return { ok: false, why: 'value differs at ' + k };
  }
  return { ok: true };
}

async function main() {
  let cfgTxt;
  try { cfgTxt = fs.readFileSync(CFG, 'utf8'); } catch (e) { return fail('cannot read ' + CFG); }
  const url = (cfgTxt.match(/url:\s*"([^"]+)"/) || [])[1];
  const anon = (cfgTxt.match(/anonKey:\s*"([^"]+)"/) || [])[1];
  if (!url || !anon) return fail('could not parse url / anonKey from supabase-config.js');

  let rows;
  try {
    const res = await fetch(url.replace(/\/$/, '') + '/rest/v1/cloudskin_content?select=key,value', {
      headers: { apikey: anon, Authorization: 'Bearer ' + anon }
    });
    if (!res.ok) return fail('cloudskin_content fetch HTTP ' + res.status);
    rows = await res.json();
  } catch (e) { return fail('network error fetching cloudskin_content: ' + e.message); }
  if (!Array.isArray(rows) || !rows.length) return fail('cloudskin_content returned 0 rows (refusing to write an empty snapshot)');

  // Build the map EXACTLY like content.js does: null -> '' , String() everything.
  const map = {};
  for (const r of rows) map[r.key] = r.value == null ? '' : String(r.value);
  const sorted = {};
  Object.keys(map).sort().forEach(function (k) { sorted[k] = map[k]; });

  const nKeys = Object.keys(sorted).length;
  let valBytes = 0; for (const k in sorted) valBytes += Buffer.byteLength(sorted[k], 'utf8');
  const stamp = new Date().toISOString();

  const body =
`/* content-snapshot.js - GENERATED by scripts/bake-content.mjs. DO NOT EDIT BY HAND.
   Deploy-time snapshot of the CloudSkin Content Studio (table cloudskin_content).
   Baked ${stamp} - ${nKeys} keys, ${valBytes} value bytes.
   Loaded SYNCHRONOUSLY before js/content.js so the owner's photos / link targets /
   text / product-control flags paint on the FIRST frame with no network wait.
   content.js still fetches Supabase live afterwards to apply any post-deploy edits.
   >>> AUTO-BAKED by scripts/deploy.mjs on every deploy (keeps snapshot == live). <<< */
window.CLOUDSKIN_CONTENT_SNAPSHOT = ${JSON.stringify(sorted, null, 2)};
`;

  // VERIFY before writing: re-parse and deep-equal against the live map (guards the
  // no-flash invariant even if JSON.stringify / the format ever drifts).
  let parsed;
  try { parsed = JSON.parse(body.slice(body.indexOf('{'), body.lastIndexOf('}') + 1)); }
  catch (e) { return fail('generated snapshot is not valid JSON'); }
  const dk = deepEqual(parsed, map);
  if (!dk.ok) return fail('generated snapshot does not equal live content: ' + dk.why);

  if (CHECK) { console.log(`--check: WOULD bake ${nKeys} keys / ${valBytes} value bytes (deep-equals live: YES). Not written.`); return; }
  fs.writeFileSync(OUT, body);
  console.log(`baked ${nKeys} keys / ${valBytes} value bytes -> js/content-snapshot.js (deep-equals live: YES)`);
}

main();
