/* ============================================================
   CLOUDSKIN, Journal sitemap generator (headless WordPress)
   ------------------------------------------------------------
   Rewrites the <url> block between the BLOG:START / BLOG:END
   markers in ../sitemap.xml with one entry per live WordPress
   post, as cloudskin.com/blog/<slug> URLs (so the SEO value
   lands on the main domain, not the WP host).

   Two ways to use it:
     1) As a LIBRARY from scripts/gen-blog.mjs:
          import { writeSitemap } from "./gen-sitemap.mjs";
          writeSitemap([{ slug, lastmod }, ...]);
        (gen-blog already fetched the posts, so no second WP call.)
     2) As a STANDALONE CLI (still supported for manual runs):
          node scripts/gen-sitemap.mjs
          node scripts/gen-sitemap.mjs https://.../wp-json/wp/v2
          CLOUDSKIN_WP_URL=https://.../wp-json/wp/v2 node scripts/gen-sitemap.mjs

   Zero dependencies (Node 18+ built-in fetch). In the deploy
   pipeline the sitemap is regenerated by gen-blog; run this
   standalone only for an ad-hoc refresh. If no WP URL is set it
   leaves the sample entries untouched and exits cleanly.
   ============================================================ */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(HERE, "..");
const SITE = "https://www.cloudskin.com";
const SITEMAP = path.join(ROOT, "sitemap.xml");

const iso = (d) => { const x = new Date(d); return isNaN(x) ? "" : x.toISOString().slice(0, 10); };
const xmlEsc = (s) => String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");

export function readConfiguredWP() {
  try {
    const src = fs.readFileSync(path.join(ROOT, "js", "blog-config.js"), "utf8");
    const url = (src.match(/url\s*:\s*["']([^"']*)["']/) || [])[1] || "";
    const lang = (src.match(/lang\s*:\s*["']([^"']*)["']/) || [])[1] || "";
    return { url, lang };
  } catch { return { url: "", lang: "" }; }
}

/* Build the <url> block for the Journal posts.
   posts: [{ slug, lastmod, langs }]
     lastmod = a date the Date ctor accepts, or ""
     langs   = OPTIONAL array of non-English language codes that have a real
               translated page. When present, one <url> is emitted per language
               (English + each lang) and every entry carries xhtml:link hreflang
               alternates linking all versions + x-default (Google's recommended
               multilingual-sitemap shape; requires xmlns:xhtml on <urlset>).
               Absent/empty -> a single English <url> (backward compatible). */
export function buildBlogBlock(posts) {
  return posts.map((p) => {
    const langs = Array.isArray(p.langs) ? p.langs.filter(Boolean) : [];
    const codes = ["en"].concat(langs);                 // English is always the source
    const lastmod = p.lastmod ? iso(p.lastmod) : "";
    const urlFor = (code) => code === "en"
      ? SITE + "/blog/" + xmlEsc(p.slug)
      : SITE + "/blog/" + xmlEsc(code) + "/" + xmlEsc(p.slug);
    const alts = codes.length > 1
      ? codes.map((c) => '    <xhtml:link rel="alternate" hreflang="' + xmlEsc(c) + '" href="' + urlFor(c) + '"/>')
          .concat('    <xhtml:link rel="alternate" hreflang="x-default" href="' + urlFor("en") + '"/>')
          .join("\n") + "\n"
      : "";
    return codes.map((code) =>
      "  <url>\n" +
      "    <loc>" + urlFor(code) + "</loc>\n" +
      (lastmod ? "    <lastmod>" + lastmod + "</lastmod>\n" : "") +
      alts +
      "    <changefreq>monthly</changefreq>\n" +
      "    <priority>" + (code === "en" ? "0.7" : "0.6") + "</priority>\n" +
      "  </url>"
    ).join("\n");
  }).join("\n");
}

/* Rewrite ../sitemap.xml BLOG:START..BLOG:END with the given posts. */
export function writeSitemap(posts) {
  if (!Array.isArray(posts) || !posts.length) throw new Error("writeSitemap: no posts given");
  const block = buildBlogBlock(posts);
  let xml = fs.readFileSync(SITEMAP, "utf8");
  const startRe = /<!-- BLOG:START[^>]*-->/;
  const endRe = /<!-- BLOG:END -->/;
  if (!startRe.test(xml) || !endRe.test(xml)) throw new Error("BLOG:START / BLOG:END markers not found in sitemap.xml");
  xml = xml.replace(/<!-- BLOG:START[^>]*-->[\s\S]*?<!-- BLOG:END -->/,
    "<!-- BLOG:START (auto-generated from the WordPress feed on " + new Date().toISOString().slice(0, 10) + ") -->\n" +
    block + "\n  <!-- BLOG:END -->");
  fs.writeFileSync(SITEMAP, xml);
  return posts.length;
}

/* ---- standalone CLI: fetch WP, then writeSitemap() ---- */
async function cli() {
  const cfg = readConfiguredWP();
  const base = (process.argv[2] || process.env.CLOUDSKIN_WP_URL || cfg.url || "").replace(/\/+$/, "");
  const langQ = cfg.lang ? "&lang=" + encodeURIComponent(cfg.lang) : "";
  if (!base) {
    console.log("[gen-sitemap] No WordPress URL configured (js/blog-config.js url is empty). Sample entries left as-is.");
    return;
  }
  const url = base + "/posts?per_page=100&_fields=slug,modified,modified_gmt&orderby=modified&order=desc" + langQ;
  const r = await fetch(url, { headers: { Accept: "application/json" } });
  if (!r.ok) throw new Error("WordPress HTTP " + r.status + " for " + url);
  const raw = await r.json();
  if (!Array.isArray(raw) || !raw.length) throw new Error("WordPress returned no posts");
  const posts = raw.map((p) => ({ slug: p.slug, lastmod: p.modified_gmt ? p.modified_gmt + "Z" : p.modified }));
  const n = writeSitemap(posts);
  console.log("[gen-sitemap] Wrote " + n + " Journal entries to sitemap.xml from " + base);
}

const runDirectly = process.argv[1] && pathToFileURL(process.argv[1]).href === import.meta.url;
if (runDirectly) cli().catch((e) => { console.error("[gen-sitemap] Failed:", e.message); process.exit(1); });
