import flips from '@/data/orientation-flips.json';

/**
 * Product photos whose primary shot faces toe-RIGHT and should be mirrored so the
 * whole catalogue presents toe-LEFT on the cards. Generated by scripts/orient-all.mjs
 * (geometric heel-vs-toe detection) and verified against result montages.
 */
const flipSet = new Set(flips as string[]);

export const shouldFlip = (slug: string): boolean => flipSet.has(slug);
