begin;
insert into public.artists (slug, name, styles, locations, portrait, bio_el, bio_en, instagram, sort, visible) values ('nikos', 'Nikos', array['Realism','Black & grey'], array['glyfada'], '/images/artists/nikos.jpg', 'Ο Νίκος ζει στο φωτορεαλιστικό μαύρο & γκρι: πορτρέτα, ζώα και μεγάλα κομμάτια φτιαγμένα να κρατούν μια ζωή.', 'Photoreal black & grey is where Nikos lives: portraits, animals and large-scale pieces built to last a lifetime.', null, 0, true) on conflict (slug) do nothing;
insert into public.portfolio_items (artist_slug, src, ar, sort) values ('nikos', '/images/tattoo/tattoo-01.jpg', 0.563, 0);
insert into public.portfolio_items (artist_slug, src, ar, sort) values ('nikos', '/images/tattoo/tattoo-02.jpg', 0.563, 1);
insert into public.portfolio_items (artist_slug, src, ar, sort) values ('nikos', '/images/tattoo/tattoo-03.jpg', 0.563, 2);
insert into public.portfolio_items (artist_slug, src, ar, sort) values ('nikos', '/images/tattoo/tattoo-04.jpg', 0.562, 3);
insert into public.portfolio_items (artist_slug, src, ar, sort) values ('nikos', '/images/tattoo/tattoo-05.jpg', 0.563, 4);
insert into public.portfolio_items (artist_slug, src, ar, sort) values ('nikos', '/images/tattoo/tattoo-06.jpg', 0.563, 5);
insert into public.portfolio_items (artist_slug, src, ar, sort) values ('nikos', '/images/tattoo/tattoo-07.jpg', 0.563, 6);
insert into public.portfolio_items (artist_slug, src, ar, sort) values ('nikos', '/images/tattoo/tattoo-08.jpg', 0.563, 7);
insert into public.portfolio_items (artist_slug, src, ar, sort) values ('nikos', '/images/tattoo/tattoo-09.jpg', 1, 8);
insert into public.portfolio_items (artist_slug, src, ar, sort) values ('nikos', '/images/tattoo/tattoo-10.jpg', 1, 9);
insert into public.portfolio_items (artist_slug, src, ar, sort) values ('nikos', '/images/tattoo/tattoo-11.jpg', 0.563, 10);
insert into public.portfolio_items (artist_slug, src, ar, sort) values ('nikos', '/images/tattoo/tattoo-12.jpg', 0.563, 11);
insert into public.artists (slug, name, styles, locations, portrait, bio_el, bio_en, instagram, sort, visible) values ('broker-diaz', 'Broker Diaz', array['Lettering','Script','Graphic'], array['glyfada'], '/images/artists/broker.jpg', 'Ο ειδικός των γραμμάτων στο στούντιο: χειροποίητη καλλιγραφία, custom blackletter και graphic που διαβάζεται καθαρά από κοντά και από μακριά.', 'The studio''s lettering specialist: hand-built script, custom blackletter and graphic work that reads as cleanly across the room as up close.', null, 1, true) on conflict (slug) do nothing;
insert into public.portfolio_items (artist_slug, src, ar, sort) values ('broker-diaz', '/images/work/broker-01.jpg', 1.055, 0);
insert into public.portfolio_items (artist_slug, src, ar, sort) values ('broker-diaz', '/images/work/broker-02.jpg', 1, 1);
insert into public.portfolio_items (artist_slug, src, ar, sort) values ('broker-diaz', '/images/work/broker-03.jpg', 1, 2);
insert into public.portfolio_items (artist_slug, src, ar, sort) values ('broker-diaz', '/images/work/broker-04.jpg', 1, 3);
insert into public.portfolio_items (artist_slug, src, ar, sort) values ('broker-diaz', '/images/work/broker-05.jpg', 1, 4);
insert into public.portfolio_items (artist_slug, src, ar, sort) values ('broker-diaz', '/images/work/broker-06.jpg', 1, 5);
insert into public.portfolio_items (artist_slug, src, ar, sort) values ('broker-diaz', '/images/work/broker-07.jpg', 1, 6);
insert into public.portfolio_items (artist_slug, src, ar, sort) values ('broker-diaz', '/images/work/broker-08.jpg', 0.814, 7);
insert into public.portfolio_items (artist_slug, src, ar, sort) values ('broker-diaz', '/images/work/broker-09.jpg', 1, 8);
insert into public.portfolio_items (artist_slug, src, ar, sort) values ('broker-diaz', '/images/work/broker-10.jpg', 1, 9);
insert into public.portfolio_items (artist_slug, src, ar, sort) values ('broker-diaz', '/images/work/broker-11.jpg', 0.954, 10);
insert into public.portfolio_items (artist_slug, src, ar, sort) values ('broker-diaz', '/images/work/broker-12.jpg', 1, 11);
insert into public.artists (slug, name, styles, locations, portrait, bio_el, bio_en, instagram, sort, visible) values ('kostas', 'Kostas', array['Colour','Graphic','Trash polka'], array['glyfada','corfu'], '/images/artists/kostas.jpg', 'Ο Κώστας σπρώχνει το χρώμα και το graphic: trash-polka, watercolour και pop-art, μαζί με λεπτομερή πορτρέτα σε μαύρο & γκρι.', 'Kostas pushes colour and graphic work: trash-polka, watercolour and pop-art pieces alongside detailed black & grey portraits.', null, 2, true) on conflict (slug) do nothing;
insert into public.portfolio_items (artist_slug, src, ar, sort) values ('kostas', '/images/work/kostas-01.jpg', 0.8, 0);
insert into public.portfolio_items (artist_slug, src, ar, sort) values ('kostas', '/images/work/kostas-02.jpg', 0.857, 1);
insert into public.portfolio_items (artist_slug, src, ar, sort) values ('kostas', '/images/work/kostas-03.jpg', 0.8, 2);
insert into public.portfolio_items (artist_slug, src, ar, sort) values ('kostas', '/images/work/kostas-04.jpg', 0.8, 3);
insert into public.portfolio_items (artist_slug, src, ar, sort) values ('kostas', '/images/work/kostas-05.jpg', 0.807, 4);
insert into public.portfolio_items (artist_slug, src, ar, sort) values ('kostas', '/images/work/kostas-06.jpg', 1, 5);
insert into public.portfolio_items (artist_slug, src, ar, sort) values ('kostas', '/images/work/kostas-07.jpg', 0.883, 6);
insert into public.portfolio_items (artist_slug, src, ar, sort) values ('kostas', '/images/work/kostas-08.jpg', 0.881, 7);
insert into public.portfolio_items (artist_slug, src, ar, sort) values ('kostas', '/images/work/kostas-09.jpg', 0.801, 8);
insert into public.portfolio_items (artist_slug, src, ar, sort) values ('kostas', '/images/work/kostas-10.jpg', 0.854, 9);
insert into public.portfolio_items (artist_slug, src, ar, sort) values ('kostas', '/images/work/kostas-11.jpg', 0.8, 10);
insert into public.portfolio_items (artist_slug, src, ar, sort) values ('kostas', '/images/work/kostas-12.jpg', 1, 11);
insert into public.artists (slug, name, styles, locations, portrait, bio_el, bio_en, instagram, sort, visible) values ('petros', 'Petros', array['Geometric','Fine-line','Ornamental'], array['corfu'], '/images/artists/petros.jpg', 'Στο στούντιο της Κέρκυρας, ο Πέτρος δουλεύει γεωμετρία και fine-line: mandalas, διακοσμητική γραμμή και λεπτά σχέδια, ακριβή και προσωπικά.', 'At our Corfu studio, Petros works in geometry and fine-line: mandalas, ornamental linework and delicate designs, precise and personal.', null, 3, true) on conflict (slug) do nothing;
insert into public.portfolio_items (artist_slug, src, ar, sort) values ('petros', '/images/work/petros-01.jpg', 1, 0);
insert into public.portfolio_items (artist_slug, src, ar, sort) values ('petros', '/images/work/petros-02.jpg', 1, 1);
insert into public.portfolio_items (artist_slug, src, ar, sort) values ('petros', '/images/work/petros-03.jpg', 1, 2);
insert into public.portfolio_items (artist_slug, src, ar, sort) values ('petros', '/images/work/petros-04.jpg', 0.998, 3);
insert into public.portfolio_items (artist_slug, src, ar, sort) values ('petros', '/images/work/petros-05.jpg', 1, 4);
insert into public.portfolio_items (artist_slug, src, ar, sort) values ('petros', '/images/work/petros-06.jpg', 1, 5);
insert into public.portfolio_items (artist_slug, src, ar, sort) values ('petros', '/images/work/petros-07.jpg', 1, 6);
insert into public.portfolio_items (artist_slug, src, ar, sort) values ('petros', '/images/work/petros-08.jpg', 0.968, 7);
insert into public.portfolio_items (artist_slug, src, ar, sort) values ('petros', '/images/work/petros-09.jpg', 1, 8);
insert into public.portfolio_items (artist_slug, src, ar, sort) values ('petros', '/images/work/petros-10.jpg', 1, 9);
insert into public.portfolio_items (artist_slug, src, ar, sort) values ('petros', '/images/work/petros-11.jpg', 1.001, 10);
insert into public.portfolio_items (artist_slug, src, ar, sort) values ('petros', '/images/work/petros-12.jpg', 1.36, 11);
insert into public.studios (id, city, city_el, street, street_el, postal_code, region, note, note_el, phone, email, lat, lng, place_ftid, place_name, maps_url, sort) values ('glyfada', 'Glyfada', 'Γλυφάδα', 'Aggelou Metaxa 33', 'Αγγέλου Μεταξά 33', '16674', 'Attica', 'Florida Mall · ground floor', 'Florida Mall · ισόγειο', '+30 211 750 6343', 'unicorntattoo2001@gmail.com', 37.8620259, 23.7536762, '0x14a1bfd1bbc938bb:0x6498f003fc02103e', 'Unicorn Tattoo & Body Piercing Studio in Glyfada', 'https://maps.google.com/?cid=7248807500156375102', 0) on conflict (id) do nothing;
insert into public.studios (id, city, city_el, street, street_el, postal_code, region, note, note_el, phone, email, lat, lng, place_ftid, place_name, maps_url, sort) values ('corfu', 'Corfu', 'Κέρκυρα', 'Eugeniou Voulgareos 26, 1st floor', 'Ευγενίου Βουλγάρεως 26, 1ος όροφος', '49100', 'Corfu', null, null, '+30 266 102 0730', 'unicorncorfu@gmail.com', 39.6237447, 19.9227925, '0x135b5ddc92800a0d:0xb4e3aee5632947ea', 'Unicorn Tattoo Corfu And Body Piercing', 'https://maps.google.com/?cid=13034454046774740970', 1) on conflict (id) do nothing;
insert into public.featured_work (style, src, alt_en, alt_el, sort) values ('realistic', '/images/tattoo/tattoo-05.jpg', 'Realistic lion tattoo by Nikos', 'Ρεαλιστικό λιοντάρι · Νίκος', 0);
insert into public.featured_work (style, src, alt_en, alt_el, sort) values ('lettering', '/images/work/broker-04.jpg', 'Script lettering by Broker Diaz', 'Καλλιγραφία · Broker Diaz', 1);
insert into public.featured_work (style, src, alt_en, alt_el, sort) values ('graphic', '/images/work/kostas-08.jpg', 'Colour graphic tattoo by Kostas', 'Έγχρωμο graphic · Κώστας', 2);
insert into public.featured_work (style, src, alt_en, alt_el, sort) values ('geometric', '/images/work/petros-10.jpg', 'Geometric mandala by Petros', 'Γεωμετρικό mandala · Πέτρος', 3);
insert into public.featured_work (style, src, alt_en, alt_el, sort) values ('realistic', '/images/work/kostas-05.jpg', 'Black & grey portrait by Kostas', 'Πορτρέτο μαύρο & γκρι · Κώστας', 4);
insert into public.instagram_posts (src, href, sort) values ('/images/tattoo/tattoo-01.jpg', 'https://www.instagram.com/unicorn.tattoo/', 0);
insert into public.instagram_posts (src, href, sort) values ('/images/work/kostas-04.jpg', 'https://www.instagram.com/unicorn.tattoo/', 1);
insert into public.instagram_posts (src, href, sort) values ('/images/work/petros-11.jpg', 'https://www.instagram.com/unicorn.tattoo/', 2);
insert into public.instagram_posts (src, href, sort) values ('/images/work/broker-07.jpg', 'https://www.instagram.com/unicorn.tattoo/', 3);
insert into public.instagram_posts (src, href, sort) values ('/images/work/kostas-08.jpg', 'https://www.instagram.com/unicorn.tattoo/', 4);
insert into public.instagram_posts (src, href, sort) values ('/images/tattoo/tattoo-07.jpg', 'https://www.instagram.com/unicorn.tattoo/', 5);
insert into public.instagram_posts (src, href, sort) values ('/images/work/petros-05.jpg', 'https://www.instagram.com/unicorn.tattoo/', 6);
insert into public.instagram_posts (src, href, sort) values ('/images/work/broker-03.jpg', 'https://www.instagram.com/unicorn.tattoo/', 7);
insert into public.instagram_posts (src, href, sort) values ('/images/work/kostas-11.jpg', 'https://www.instagram.com/unicorn.tattoo/', 8);
insert into public.piercing_photos (src, sort) values ('/images/work/work-02.jpg', 0);
insert into public.piercing_photos (src, sort) values ('/images/work/work-06.jpg', 1);
insert into public.piercing_photos (src, sort) values ('/images/work/work-09.jpg', 2);
insert into public.piercing_photos (src, sort) values ('/images/work/work-11.jpg', 3);
insert into public.piercing_photos (src, sort) values ('/images/work/work-14.jpg', 4);
insert into public.piercing_photos (src, sort) values ('/images/work/work-16.jpg', 5);
insert into public.piercing_photos (src, sort) values ('/images/work/work-18.jpg', 6);
insert into public.piercing_photos (src, sort) values ('/images/work/work-21.jpg', 7);
insert into public.piercing_photos (src, sort) values ('/images/work/work-24.jpg', 8);
insert into public.piercing_photos (src, sort) values ('/images/work/work-27.jpg', 9);
insert into public.piercing_photos (src, sort) values ('/images/work/work-30.jpg', 10);
insert into public.piercing_photos (src, sort) values ('/images/work/work-32.jpg', 11);
insert into public.site_settings (key, value) values ('social.instagram', 'https://www.instagram.com/unicorn.tattoo/') on conflict (key) do nothing;
insert into public.site_settings (key, value) values ('social.instagramHandle', '@unicorn.tattoo') on conflict (key) do nothing;
insert into public.site_settings (key, value) values ('social.facebook', 'https://www.facebook.com/unicorntattooglyfada') on conflict (key) do nothing;
insert into public.site_settings (key, value) values ('background.hero', '/images/bg/hero.jpg') on conflict (key) do nothing;
insert into public.site_settings (key, value) values ('background.cta', '/images/bg/cta.jpg') on conflict (key) do nothing;
insert into public.site_settings (key, value) values ('background.banner', '/images/bg/banner.jpg') on conflict (key) do nothing;
insert into public.site_settings (key, value) values ('background.footer', '/images/bg/footer-bg.jpg') on conflict (key) do nothing;
insert into public.site_settings (key, value) values ('piercing.introImage', '/images/work/work-06.jpg') on conflict (key) do nothing;
commit;
